language: php

matrix:
  fast_finish: true
  include:
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: 5.6
      env:
        - EXECUTE_SCRUTINIZER=true

before_script:
  - composer install --dev --no-interaction
  
script:
  - phpunit -c tests
  
after_script:
  - if [[ $EXECUTE_SCRUTINIZER == 'true' ]]; then wget https://scrutinizer-ci.com/ocular.phar || return 0 ; fi
  - if [[ $EXECUTE_SCRUTINIZER == 'true' ]]; then php ocular.phar code-coverage:upload --format=php-clover tests/log/coverage.xml || return 0 ; fi
