language: php
php:
  - 5.5
  - 5.4
  - hhvm
  
before_script:
  - composer install --dev --no-interaction
  
script:
  - phpunit -c tests
  
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/log/coverage.xml
  
matrix:
  allow_failures:
    - php: hhvm